sensor:
  - platform: command_line
    name: HeatpumpThrottleSensor_csv
    command: "python3 /addon_configs/a0d7b954_appdaemon/apps/ReadPriceData.py"
    value_template: "{{ value.split(',')[1].split(':')[1].strip() }}"
    attribute_templates:
      price: "{{ value.split(',')[0].split(':')[1].strip() }}"
      adjustment: "{{ value.split(',')[1].split(':')[1].strip() }}"