alias: Intelligent Irrigation
description: ""
trigger:
  - platform: time_pattern
    hours: /8
    minutes: "00"
    seconds: "00"
condition:
  - condition: time
    after: "04:00:00"
    before: "20:00:00"
action:
  - condition: template
    value_template: "{{ quota_multiplier > 0 }}"
  - service: switch.turn_on
    entity_id: switch.sonoff_smartrelay_1
  - service: script.turn_on
    target:
      entity_id: script.intelligent_irrigation
    data:
      variables:
        duration: "{{ '%02d:%02d:%02d' | format((10 * quota_multiplier) | round | int // 60, (10 * quota_multiplier) | round | int % 60, 0) }}"
  - delay: 
      seconds: 5  # Wait for 5 seconds before starting the repeat action
  - repeat:
      while:
        - condition: state
          entity_id: switch.sonoff_smartrelay_1
          state: "on"
      sequence:
        - service: switch.turn_off
          entity_id: switch.sonoff_smartrelay_1
        - delay: 
            seconds: 10  # Wait for 10 seconds before checking the state again
  - delay: 
      seconds: 10  # Wait for 10 seconds to give the switch time to turn off
  - condition: template
    value_template: "{{ is_state('switch.sonoff_smartrelay_1', 'on') }}"
  - service: notify.notify
    data:
      message: Failed to turn off irrigation system.
variables:
  quota_multiplier: >
    {% set greenhouse_temperature = states('sensor.sensor_i_vaxthuset_temperature') | float %}
    {% set forecasted_temperature = states('sensor.openweathermap_forecast_temperature') | float %}
    {% set forecasted_cloud_coverage = states('sensor.openweathermap_forecast_cloud_coverage') | float %}
    {% set base_quota = 2 * 24 %}
    {% set quota_multiplier = 1 %}
    {% if greenhouse_temperature > 30 %}
      {% set quota_multiplier = 2 %}
    {% elif greenhouse_temperature > 25 %}
      {% set quota_multiplier = 1 %}
    {% elif greenhouse_temperature < 10 %}
      {% set quota_multiplier = 0 %}
    {% endif %}
    {% if forecasted_temperature > 25 %}
      {% set quota_multiplier = quota_multiplier * 1.5 %}
    {% elif forecasted_temperature < 10 %}
      {% set quota_multiplier = quota_multiplier * 0.5 %}
    {% endif %}
    {% if forecasted_cloud_coverage < 25 %}
      {% set quota_multiplier = quota_multiplier * 1.5 %}
    {% elif forecasted_cloud_coverage > 75 %}
      {% set quota_multiplier = quota_multiplier * 0.5 %}
    {% endif %}
    {{ quota_multiplier }}