alias: Intelligent Irrigation
description: ""
trigger:
  - platform: time_pattern
    hours: /4
    minutes: "00"
    seconds: "00"
condition:
  - condition: time
    after: "04:00:00"
    before: "20:00:00"
action:
  - service: switch.turn_on
    entity_id: switch.sonoff_smartrelay_1
  - service: script.turn_on
    target:
      entity_id: script.intelligent_irrigation
    data:
      variables:
        duration: "{{ (15 * quota_multiplier) | round | int }}"
  - condition: state
    entity_id: switch.sonoff_smartrelay_1
    state: "on"
  - service: notify.notify
    data:
      message: Failed to turn off irrigation system.
variables:
  quota_multiplier: >
    {% set greenhouse_temperature =
    states('sensor.sensor_i_vaxthuset_temperature') | float %} {% set
    forecasted_temperature =
    states('sensor.openweathermap_forecast_temperature') | float %} {% set
    forecasted_cloud_coverage =
    states('sensor.openweathermap_forecast_cloud_coverage') | float %} {% set
    base_quota = 2 * 24 %} {% set quota_multiplier = 1 %} {% if
    greenhouse_temperature > 30 %}
      {% set quota_multiplier = 2 %}
    {% elif greenhouse_temperature > 25 %}
      {% set quota_multiplier = 1 %}
    {% elif greenhouse_temperature < 15 %}
      {% set quota_multiplier = 0 %}
    {% endif %} {% if forecasted_temperature > 25 %}
      {% set quota_multiplier = quota_multiplier * 1.5 %}
    {% elif forecasted_temperature < 15 %}
      {% set quota_multiplier = quota_multiplier * 0.5 %}
    {% endif %} {% if forecasted_cloud_coverage > 75 %}
      {% set quota_multiplier = quota_multiplier * 0.5 %}
    {% elif forecasted_cloud_coverage < 25 %}
      {% set quota_multiplier = quota_multiplier * 1.5 %}
    {% endif %} {{ quota_multiplier }}
